#ifndef WORD_LIST_H
#define WORD_LIST_H

//Estes conjuntos de palavras foram gerados pelo o Deepsesk AI, tal como falado com o professor.
const char *eng_word_bank1[491] = {
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
    "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
    "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
    "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
    "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
    "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
    "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
    "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
    "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
    "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
    "is", "are", "was", "were", "been", "being", "has", "had", "having", "does",
    "did", "doing", "may", "might", "must", "shall", "should", "will", "would", "can",
    "could", "ought", "need", "dare", "used", "try", "call", "ask", "need", "feel",
    "become", "leave", "put", "mean", "keep", "let", "begin", "seem", "help", "talk",
    "turn", "start", "might", "show", "hear", "play", "run", "move", "like", "live",
    "believe", "hold", "bring", "happen", "write", "provide", "sit", "stand", "lose", "pay",
    "meet", "include", "continue", "set", "learn", "change", "lead", "understand", "watch", "follow",
    "stop", "create", "speak", "read", "allow", "add", "spend", "grow", "open", "walk",
    "win", "offer", "remember", "love", "consider", "appear", "buy", "wait", "serve", "die",
    "send", "expect", "build", "stay", "fall", "cut", "reach", "kill", "remain", "suggest",
    "raise", "pass", "sell", "require", "report", "decide", "pull", "return", "explain", "wish",
    "agree", "support", "receive", "join", "reduce", "establish", "mention", "imagine", "arrive", "sleep",
    "cover", "apply", "compare", "worry", "notice", "marry", "suppose", "manage", "discover", "improve",
    "thank", "realize", "smile", "prepare", "replace", "fill", "involve", "identify", "obtain", "forget",
    "wonder", "recognize", "indicate", "intend", "complete", "deny", "prefer", "refer", "relate", "survive",
    "publish", "suffer", "describe", "remind", "promise", "accept", "admit", "assume", "belong", "consist",
    "contribute", "depend", "exist", "insist", "participate", "prove", "reflect", "regard", "relax", "tend",
    "affect", "attract", "avoid", "beat", "bend", "bite", "blow", "burn", "care", "carry",
    "catch", "check", "climb", "collect", "count", "cry", "dance", "draw", "drink", "drive",
    "eat", "enjoy", "enter", "exit", "fix", "fly", "forgive", "freeze", "gather", "greet",
    "guess", "hang", "hide", "hit", "hug", "hunt", "hurt", "jump", "kick", "kiss",
    "knock", "laugh", "lay", "lie", "lift", "listen", "look", "measure", "melt", "mix",
    "nod", "notice", "obey", "observe", "organize", "pack", "paint", "pat", "point", "press",
    "protect", "punch", "push", "race", "record", "repair", "respect", "ride", "ring", "roll",
    "rub", "save", "scream", "search", "separate", "shake", "shout", "sing", "slap", "slide",
    "smell", "solve", "spread", "squeeze", "stare", "step", "stretch", "swim", "swing", "teach",
    "tear", "throw", "touch", "train", "trust", "try", "tug", "visit", "vote", "wash",
    "wave", "weigh", "whisper", "wink", "wipe", "wish", "wrestle", "yawn", "yell", "zip",
    "able", "above", "absent", "absolute", "academic", "acceptable", "accurate", "active", "actual", "acute",
    "additional", "adequate", "adjacent", "administrative", "adorable", "advanced", "adverse", "affordable", "afraid", "aggressive",
    "agreeable", "alert", "alive", "amazing", "ambitious", "amused", "ancient", "angry", "annual", "another",
    "anxious", "apparent", "applicable", "appropriate", "arbitrary", "artistic", "ashamed", "assistant", "associated", "atomic",
    "attractive", "automatic", "available", "average", "aware", "awful", "awkward", "backward", "bad", "balanced",
    "bare", "basic", "beautiful", "beneficial", "best", "better", "big", "biological", "bitter", "bizarre",
    "black", "blank", "blind", "blonde", "bloody", "blue", "bold", "boring", "born", "both",
    "bouncy", "brainy", "brave", "breakable", "breezy", "brief", "bright", "brilliant", "broad", "broken",
    "bumpy", "burning", "busy", "calm", "capable", "careful", "casual", "cautious", "central", "certain",
    "charming", "cheap", "cheerful", "chemical", "chief", "chilly", "chubby", "circular", "classic", "clean",
    "clear", "clever", "close", "closed", "cloudy", "clumsy", "coarse", "cold", "collective", "colorful",
    "colossal"}; 
        
const char *eng_word_bank2[491] = {"common", "compact", "compatible", "competitive", "complete", "complex", "complicated",
    "comprehensive", "conceptual", "concerned", "concrete", "confident", "confused", "conscious", "conservative", "considerable", "consistent",
    "constant", "contemporary", "content", "contrary", "contrasting", "controversial", "convenient", "conventional", "cool", "cooperative",
    "coordinated", "corporate", "correct", "costly", "courageous", "crazy", "creative", "creepy", "criminal", "critical",
    "crooked", "crowded", "cruel", "cuddly", "cultural", "curious", "curly", "curved", "cute", "daily",
    "damaged", "damp", "dangerous", "dark", "dead", "deaf", "dear", "decent", "decisive", "deep",
    "defensive", "definite", "deliberate", "delicate", "delicious", "delightful", "demanding", "dense", "dental", "dependent",
    "desirable", "desperate", "detailed", "determined", "developed", "developing", "devoted", "different", "difficult", "digital",
    "diplomatic", "direct", "dirty", "disabled", "disappointed", "disastrous", "disciplinary", "distant", "distinct", "distinctive",
    "diverse", "divine", "domestic", "dominant", "double", "doubtful", "dramatic", "dreadful", "drunk", "dry",
    "dual", "due", "dull", "dusty", "dutch", "dying", "dynamic", "eager", "early", "easy",
    "economic", "educational", "effective", "efficient", "elaborate", "elastic", "elderly", "electric", "elegant", "eligible",
    "embarrassed", "emerging", "emotional", "empirical", "empty", "enchanted", "encouraging", "endless", "energetic", "enormous",
    "enthusiastic", "entire", "environmental", "equal", "equivalent", "essential", "established", "estimated", "ethical", "eventual",
    "everyday", "evident", "evil", "exact", "excellent", "exceptional", "excess", "excessive", "excited", "exciting",
    "exclusive", "existing", "exotic", "expensive", "experienced", "experimental", "explicit", "express", "extended", "extensive",
    "external", "extra", "extraordinary", "extreme", "faint", "fair", "faithful", "familiar", "famous", "fancy",
    "fantastic", "far", "fascinating", "fashionable", "fast", "fat", "fatal", "favorable", "favorite", "federal",
    "fellow", "female", "feminine", "few", "fierce", "filthy", "final", "financial", "fine", "firm",
    "first", "fitting", "fixed", "flaky", "flat", "flexible", "fluffy", "fluid", "flying", "folding",
    "following", "fond", "foolish", "formal", "formidable", "forthcoming", "fortunate", "forward", "fragile", "frail",
    "frank", "frantic", "free", "frequent", "fresh", "friendly", "frightened", "front", "frozen", "full",
    "fun", "functional", "funny", "furious", "fuzzy", "gaseous", "general", "generous", "gentle", "genuine",
    "giant", "gifted", "gigantic", "giving", "glamorous", "glaring", "glass", "global", "glorious", "golden",
    "good", "gorgeous", "graceful", "gradual", "grand", "grateful", "grave", "gray", "greasy", "great",
    "greedy", "green", "grey", "grieving", "grim", "gross", "grotesque", "growing", "grubby", "grumpy",
    "guilty", "handsome", "happy", "hard", "harsh", "head", "healthy", "heavy", "helpful", "helpless",
    "hidden", "high", "hilarious", "hissing", "historic", "hollow", "holy", "homely", "honest", "horizontal",
    "horny", "horrible", "hostile", "hot", "huge", "human", "hungry", "hurt", "hushed", "husky",
    "icy", "ideal", "identical", "idle", "ignorant", "ill", "illegal", "imaginary", "immediate", "immense",
    "imperial", "implicit", "important", "impossible", "impressive", "improved", "inadequate", "inappropriate", "incapable", "incredible",
    "indian", "indifferent", "indirect", "individual", "industrial", "inevitable", "influential", "informal", "inherent", "initial",
    "injured", "inner", "innocent", "innovative", "inquisitive", "insane", "insecure", "inside", "instant", "instinctive",
    "institutional", "intelligent", "intense", "interactive", "interior", "internal", "international", "intimate", "invisible", "involved",
    "irish", "irrelevant", "irritated", "itchy", "jealous", "jittery", "joint", "jolly", "joyous", "judicial",
    "juicy", "junior", "just", "keen", "key", "kind", "known", "korean", "large", "late",
    "latin", "lazy", "leading", "left", "legal", "lethal", "level", "light", "like", "literary",
    "little", "live", "lively", "local", "logical", "lonely", "long", "loose", "lost", "loud",
    "lovely", "low", "loyal", "lucky", "mad", "magic", "magnetic", "main", "major", "male",
    "mammoth", "managerial", "manual", "many", "marginal", "marine", "marked", "married", "marvelous", "masculine",
    "massive", "mathematical", "mature", "maximum", "mean", "mechanical", "medical", "medieval", "medium", "melodic",
    "melted", "mental", "mere", "metropolitan", "middle", "mighty", "mild", "military", "miniature", "minimal",
    "minimum", "minor", "minute", "miserable", "misleading", "missing", "mixed", "mobile", "moderate", "modern",
    "modest", "molecular", "monetary", "monthly", "moral", "motionless", "muddy", "multiple", "muscular", "mushy",
    "musical", "mutual", "mysterious", "naked", "narrow", "nasty", "national", "native", "natural", "naughty",
    "naval", "near", "nearby", "neat", "necessary", "negative", "neighboring", "nervous", "net", "neutral",
    "new", "next", "nice", "noble", "noisy", "normal", "northern", "nosy", "notable", "novel",
    "nuclear", "numerous", "nursing", "nutty", "obedient", "objective", "obliged", "obnoxious", "obvious", "occasional",
    "occupational", "odd", "official", "ok", "old", "olympic", "only", "open", "operational", "opposite",
    "optimistic", "oral", "orange", "ordinary"};
    
const char *eng_word_bank3[492] =  {"original", "orthodox", "other", "outdoor",
    "outer", "outstanding", "overall", "overseas", "overwhelming", "painful", "pale", "panicky", "parallel", "parental",
    "parliamentary", "partial", "particular", "passing", "passive", "past", "patient", "peaceful", "peculiar", "perfect",
    "permanent", "persistent", "personal", "petite", "philosophical", "physical", "pink", "plain", "planned", "plastic",
    "pleasant", "pleased", "poised", "polish", "polite", "political", "poor", "popular", "positive", "possible",
    "potential", "powerful", "practical", "precious", "precise", "preferred", "pregnant", "preliminary", "premier", "prepared",
    "present", "presidential", "pretty", "previous", "prickly", "primary", "prime", "principal", "printed", "prior",
    "private", "probable", "productive", "professional", "profitable", "profound", "progressive", "prominent", "proper", "proposed",
    "prosperous", "protective", "proud", "provincial", "public", "puny", "pure", "purple", "puzzled", "quaint",
    "qualified", "quick", "quiet", "racial", "radical", "rainy", "random", "rapid", "rare", "rational",
    "raw", "ready", "real", "realistic", "rear", "reasonable", "recent", "red", "reduced", "redundant",
    "regional", "registered", "regular", "relative", "relaxed", "relevant", "reliable", "relieved", "religious", "reluctant",
    "remaining", "remarkable", "remote", "renewed", "representative", "repulsive", "required", "resident", "residential", "resonant",
    "respectable", "respective", "responsible", "resulting", "retail", "retired", "revolutionary", "rich", "ridiculous", "right",
    "rigid", "ripe", "rising", "rival", "roasted", "robust", "rolling", "romantic", "rotten", "rough",
    "round", "royal", "rubber", "rude", "ruling", "running", "rural", "sacred", "sad", "safe",
    "salty", "same", "satisfactory", "satisfied", "scared", "scary", "scattered", "scientific", "scornful", "scrawny",
    "screeching", "secondary", "secret", "secure", "select", "selected", "selfish", "semantic", "senior", "sensible",
    "sensitive", "separate", "serious", "severe", "sexual", "shaggy", "shaky", "shallow", "shared", "sharp",
    "shiny", "shocked", "short", "shrill", "shy", "sick", "significant", "silent", "silky", "silly",
    "similar", "simple", "single", "skilled", "skinny", "sleepy", "slight", "slim", "slimy", "slippery",
    "slow", "small", "smart", "smiling", "smoggy", "smooth", "social", "soft", "solar", "sole",
    "solid", "solitary", "sophisticated", "sore", "sorry", "sound", "sour", "southern", "spare", "sparkling",
    "spatial", "special", "specific", "spectacular", "spicy", "spiritual", "splendid", "spontaneous", "sporting", "spotless",
    "spotty", "square", "squealing", "stable", "stale", "standard", "static", "statistical", "steady", "steep",
    "sticky", "stiff", "still", "stimulating", "straight", "strategic", "strict", "striking", "striped", "strong",
    "structural", "stuck", "stupid", "subjective", "subsequent", "substantial", "subtle", "successful", "sudden", "sufficient",
    "suitable", "sunny", "super", "superb", "superior", "supporting", "supposed", "supreme", "sure", "surprised",
    "surprising", "surrounding", "surviving", "suspicious", "sweet", "swift", "symbolic", "sympathetic", "systematic", "tall",
    "tame", "tart", "tasteless", "tasty", "technical", "technological", "teenage", "temporary", "tender", "tense",
    "terrible", "territorial", "testy", "then", "theoretical", "thick", "thin", "thirsty", "thoughtful", "thoughtless",
    "thundering", "tight", "tiny", "tired", "top", "tory", "total", "tough", "towering", "tragic",
    "trained", "tremendous", "tricky", "tropical", "troubled", "typical", "ugly", "ultimate", "unable", "unacceptable",
    "unaware", "uncertain", "unchanged", "uncomfortable", "unconscious", "underground", "underlying", "unemployed", "uneven", "unexpected",
    "unfair", "unfortunate", "unhappy", "uniform", "uninterested", "unique", "universal", "unknown", "unlikely", "unnecessary",
    "unpleasant", "unsightly", "unusual", "upset", "uptight", "urban", "urgent", "used", "useful", "useless",
    "usual", "vague", "valid", "valuable", "variable", "varied", "vast", "verbal", "vertical", "very",
    "victorious", "violent", "visible", "visual", "vital", "vivacious", "vivid", "vocational", "voiceless", "voluntary",
    "vulnerable", "wandering", "warm", "wasteful", "watery", "weak", "wealthy", "weary", "weekly", "weird",
    "welcome", "well", "western", "wet", "whispering", "whole", "wicked", "wide", "wild", "willing",
    "wise", "witty", "wonderful", "wooden", "worried", "worthwhile", "worthy", "written", "wrong", "yellow",
    "young", "yummy", "zany", "zealous", "zesty", "zippy", "abandoned", "able", "absolute", "abstract", "abundant", "accurate", "acidic", "active", "adorable", "advanced",
    "adventurous", "affectionate", "aggressive", "agreeable", "alert", "alive", "amazing", "ambitious", "ancient", "angry",
    "annoying", "anxious", "arrogant", "artistic", "assertive", "astonishing", "attractive", "authentic", "automatic", "available",
    "average", "awkward", "bad", "balanced", "bare", "basic", "beautiful", "beneficial", "bitter", "bizarre",
    "black", "blank", "bleak", "blissful", "bold", "boring", "bouncy", "brave", "brief", "bright",
    "brilliant", "broad", "broken", "busy", "calm", "careful", "careless", "casual", "central", "certain",
    "charming", "cheap", "cheerful", "chief", "childish", "chilly", "circular", "classical", "clean", "clear",
    "clever", "close", "cloudy", "clumsy", "coarse", "colorful", "comfortable", "common", "complex", "complicated",
    "confident"
}; 

const char *pt_word_bank1[491] = {
    "a", "abaixo", "acao", "adeus", "agora", "ainda", "alem", "algo", "alguem", 
    "algum", "alguma", "algumas", "alguns", "ali", "amor", "andar", "ano", "anos", 
    "antes", "ao", "aos", "apenas", "apoio", "apos", "aquela", "aquelas", "aquele", 
    "aqueles", "aqui", "aquilo", "area", "as", "assim", "ate", "atras", "atuais", 
    "atual", "auto", "baixo", "bem", "boa", "boas", "bom", "bons", "breve", "cada", 
    "caminho", "casa", "caso", "cento", "certa", "certas", "certeza", "certo", 
    "certos", "cima", "cinco", "coisa", "coisas", "com", "como", "conselho", 
    "contra", "contudo", "cor", "cuja", "cujas", "cujo", "cujos", "da", "daquela", 
    "daquelas", "daquele", "daqueles", "dar", "das", "de", "debaixo", "dela", 
    "delas", "dele", "deles", "demais", "dentro", "depois", "desde", "dessa", 
    "dessas", "desse", "desses", "desta", "destas", "deste", "destes", "deve", 
    "devem", "dever", "dez", "dezesseis", "dezesseis", "dezoito", "dia", "diante", 
    "dias", "diferente", "diferentes", "dificil", "dinheiro", "direita", "direito", 
    "disse", "dizer", "do", "dois", "dos", "doze", "duas", "duvida", "e", "ela", 
    "elas", "ele", "eles", "em", "embora", "enquanto", "entre", "entao", "era", 
    "eram", "eramos", "escola", "essa", "essas", "esse", "esses", "esta", "estado", 
    "estamos", "estar", "estas", "estava", "estavam", "este", "esteja", "estejam", 
    "estejamos", "estes", "esteve", "estive", "estivemos", "estiver", "estivera", 
    "estiveram", "estiverem", "estivermos", "estivesse", "estivessem", "estou", 
    "eu", "exemplo", "faca", "facam", "faco", "fazer", "feita", "feitas", "feito", 
    "feitos", "fez", "fim", "final", "foi", "fomos", "for", "fora", "foram", 
    "forem", "forma", "formos", "fosse", "fossem", "frente", "fui", "geral", 
    "grande", "grandes", "grupo", "ha", "hoje", "hora", "horas", "idade", "igual", 
    "incluso", "isso", "isto", "ja", "la", "lado", "lhe", "lhes", "ligacao", 
    "local", "logo", "longe", "longo", "lugar", "maior", "maioria", "mais", "mal", 
    "maneira", "mas", "massa", "me", "meio", "menor", "menos", "mes", "mesma", 
    "mesmas", "mesmo", "mesmos", "meu", "meus", "mil", "minha", "minhas", "modo", 
    "momento", "muito", "muitos", "na", "nada", "nao", "naquela", "naquelas", 
    "naquele", "naqueles", "nas", "nem", "nenhum", "nenhuma", "nessa", "nessas", 
    "nesse", "nesses", "nesta", "nestas", "neste", "nestes", "ninguem", "nivel", 
    "no", "noite", "nome", "nos", "nossa", "nossas", "nosso", "nossos", "nova", 
    "novas", "nove", "novo", "novos", "num", "numa", "numero", "nunca", "o", 
    "obra", "obrigado", "oitava", "oitavo", "oito", "onde", "ontem", "onze", 
    "os", "ou", "outra", "outras", "outro", "outros", "pais", "palavra", "para", 
    "parece", "parte", "partir", "paucas", "pela", "pelas", "pelo", "pelos", 
    "pequena", "pequenas", "pequeno", "pequenos", "per", "perante", "perto", 
    "pode", "podem", "poder", "podia", "ponto", "pontos", "por", "porem", 
    "porque", "posicao", "possivel", "posso", "pouca", "pouco", "poucos", 
    "primeira", "primeiras", "primeiro", "primeiros", "propria", "proprias", 
    "proprio", "proprios", "quais", "quaisquer", "qual", "qualquer", "quando", 
    "quanto", "quantos", "quarta", "quarto", "quatro", "que", "quem", "quer", 
    "quero", "questao", "quinta", "quinto", "quinze", "relacao", "sabe", "saber", 
    "se", "segunda", "segundo", "sei", "seis", "seja", "sejam", "sejamos", "sem", 
    "sempre", "sendo", "ser", "sera", "serao", "serei", "seremos", "seria", 
    "seriam", "sete", "setima", "setimo", "seu", "seus", "sexta", "sexto", "si", 
    "sido", "sim", "sistema", "so", "sob", "sobre", "sois", "somos", "sou", "sua", 
    "suas", "tal", "talvez", "tambem", "tanta", "tantas", "tanto", "tarde", "te", 
    "tem", "tema", "temos", "tempo", "tendes", "tenha", "tenham", "tenhamos", 
    "tenho", "tens", "ter", "terceira", "terceiro", "teria", "teriam", "teu", 
    "teus", "teve", "ti", "tido", "tinha", "tinham", "tipo", "tive", "tivemos", 
    "tiver", "tivera", "tiveram", "tiverem", "tivermos", "tivesse", "tivessem", 
    "toda", "todas", "todo", "todos", "trabalho", "tres", "treze", "tu", "tua", 
    "tuas", "tudo", "um", "uma", "umas", "uns", "vai", "vais", "valor", "vamos", 
    "varia", "varias", "varios", "vazia", "vazio", "veja", "vem", "vens", "ver", 
    "vez", "vezes", "viagem", "vida", "vindo", "vinte", "vir", "voce", "voces", 
    "vos", "vossa", "vossas", "vosso", "vossos", "zero", "zona","acordo", "agua", "ajuda", "alegria", "alto", 
    "amigo", "amigos", "andar", "animal", "antes", "apagar", "apoio", "aprender", 
    "aproveitar", "area", "arma", "arte", "arvore", "atencao", "atras", "aula",     
    "aviao"
};


const char *pt_word_bank2[491] = {
    "aberto", "acaso", "acima", "acordo", "agua", "ajuda", "alegria", "alto", 
    "amigo", "amigos", "andar", "animal", "antes", "apagar", "apoio", "aprender", 
    "aproveitar", "area", "arma", "arte", "arvore", "atencao", "atras", "aula",     
    "aviao", "bala", "banco", "banda", "barco", "bater", "bela", "beleza", "bem", 
    "boca", "bola", "bonito", "branco", "brasil", "bravo", "busca", "cabelo", 
    "cabo", "cadeira", "cafe", "cama", "campo", "canto", "capaz", "carne", 
    "carro", "carta", "casa", "casal", "castelo", "cavalo", "cedo", "celular", 
    "certo", "chamar", "chave", "chegar", "cheio", "chover", "chuva", "cidade", 
    "claro", "clube", "copo", "corpo", "correr", "corte", "couro", "crianca", 
    "cuidado", "culpa", "cultura", "danca", "dedo", "deixar", "dente", "depois", 
    "deserto", "desejo", "detalhe", "dia", "dica", "dificil", "dinheiro", 
    "direito", "doce", "doente", "dor", "dormir", "duro", "eco", "edificio", 
    "efeito", "eixo", "elefante", "elevador", "embaixo", "energia", "engracado", 
    "enigma", "enorme", "entrada", "equipe", "escada", "escola", "escuro", 
    "espaco", "especial", "esperar", "espelho", "esporte", "esquerda", "estado", 
    "estrada", "estranho", "estudar", "etapa", "exato", "exemplo", "exercicio", 
    "explicar", "faca", "fada", "falar", "fama", "familia", "fardo", "fase", 
    "fato", "fazer", "feliz", "ferro", "filho", "filme", "fio", "fogo", "folha", 
    "fome", "fonte", "forma", "forte", "foto", "fraco", "frente", "frio", "fuga", 
    "fundo", "futuro", "gato", "gente", "gol", "gosto", "grande", "grao", "grito", 
    "grupo", "guerra", "guia", "habito", "historia", "homem", "honra", "hora", 
    "ideia", "igreja", "ilha", "imagem", "irmao", "irmaos", "jardim", "jogo", 
    "jovem", "joia", "lago", "lamento", "lata", "leao", "leite", "leitura", 
    "lenda", "lenco", "lento", "letra", "livro", "loja", "lua", "luz", "madeira", 
    "mae", "maior", "mao", "mar", "marca", "marido", "mascara", "medo", "mel", 
    "menina", "menino", "mesa", "metal", "metro", "meu", "mexer", "mico", "mil", 
    "mim", "mina", "minuto", "mocinho", "moda", "moeda", "molho", "monstro", 
    "morte", "mostrar", "motor", "mundo", "muralha", "muro", "musica", "nacao", 
    "nadar", "nave", "neve", "noite", "nome", "norte", "nove", "novela", "nuvem", 
    "objeto", "oceano", "olhar", "olho", "onda", "onibus", "ordem", "orgulho", 
    "osso", "ouro", "outono", "ouvir", "ovo", "pai", "pais", "paixao", "pala", 
    "palavra", "pano", "papel", "par", "parar", "parede", "parte", "passo", 
    "pasta", "pata", "pau", "paz", "pe", "pele", "pequeno", "pera", "perder", 
    "perna", "peso", "pia", "pico", "pilar", "pintar", "pipa", "pista", "plano", 
    "planta", "pneu", "pobre", "poco", "poder", "poema", "poesia", "ponto", 
    "porco", "porta", "porto", "posar", "poste", "pote", "pouco", "pouso", 
    "povo", "praia", "prato", "preco", "prego", "premio", "preso", "prima", 
    "primo", "prisao", "proa", "prova", "pular", "pulo", "puxar", "quadro", 
    "quarto", "queda", "queijo", "quente", "quilo", "quitar", "rabo", "raio", 
    "raiva", "raiz", "rapaz", "raro", "rato", "reacao", "rede", "rei", "remar", 
    "remover", "repente", "resposta", "resto", "retrato", "reuniao", "revelar", 
    "revista", "rico", "rio", "risada", "risco", "ritmo", "rocha", "roda", 
    "rolar", "rolo", "roma", "rosa", "rosto", "roupa", "rua", "rubi", "ruim", 
    "rumo", "sabao", "saber", "sabor", "saco", "sala", "salto", "sangue", 
    "sapo", "saque", "sarda", "sede", "segredo", "selo", "semana", "semente", 
    "senhor", "sentar", "sentido", "serra", "serrar", "servo", "sexta", "sinal", 
    "sino", "siri", "sitio", "sobra", "soco", "sogra", "sogro", "sol", "soldado", 
    "solo", "sombra", "sonho", "sono", "sopro", "sorrir", "sorte", "sorvete", 
    "subir", "sujo", "sul", "sumir", "super", "tabua", "taco", "talher", "talo", 
    "tamanho", "tampa", "tango", "tanto", "tapa", "tarde", "tatu", "taxa", 
    "teatro", "teia", "temer", "templo", "tenda", "terno", "terra", "tesouro", 
    "teste", "texto", "tigre", "tijolo", "tinta", "tio", "tirar", "toca", 
    "toco", "toalha", "tolo", "tomar", "tonel", "topo", "tora", "torcer", 
    "torneio", "torno", "torre", "tosse", "touro", "trabalho", "traje", "tramar", 
    "tranca", "trapo", "trator", "trava", "trazer", "treinar", "tremer", "trem", 
    "tres", "tribo", "trocar", "trono", "tropa", "trova", "truque", "tubo", 
    "tudo", "tufao", "tumba", "tumor", "tunel", "turma", "tutor", "uivar", 
    "ultimo", "umbigo", "unha", "uniao", "urso", "urubu", "usar", "vaca", 
    "vaga", "vagem", "vai", "vaivem", "vala", "vale", "valor", "vapor", "vara", 
    "varal", "varrer", "vaso", "vassoura", "vazio", "veado", "vedar", "vegetal", 
    "veia"
};


const char *pt_word_bank3[491] = {
    "abacaxi", "abanar", "abastecer", "abelha", "aberto", "abismo", "abobora", 
    "abotoar", "abrigo", "abrir", "absurdo", "abutre", "acalmar", "acender", 
    "acertar", "achado", "acidente", "acordar", "acreditar", "acuado", "adagas", 
    "adeus", "adivinhar", "admirar", "adormecer", "adubo", "advogado", "afagar", 
    "afastar", "afetar", "afinal", "afundar", "agarrar", "agasalho", "agil", 
    "agiota", "agitar", "agora", "agradar", "agua", "aguardar", "agulha", 
    "ajudar", "ajuste", "ala", "alarme", "alavanca", "albergue", "albino", 
    "alcance", "alegre", "alerta", "alfabeto", "alga", "algema", "alho", 
    "aliado", "aliviar", "almoco", "alojar", "alpiste", "alterar", "altura", 
    "alucinar", "alugar", "aluno", "alvo", "amador", "amarelo", "ambicao", 
    "ameaca", "ameixa", "amendoim", "amigo", "amizade", "amolador", "amor", 
    "amostra", "ampola", "anciao", "andaime", "anel", "anexo", "angulo", 
    "anjo", "ano", "anotar", "ansioso", "antena", "antigo", "anuncio", "anzol", 
    "apagado", "apalpar", "apartar", "apego", "apelido", "apertar", "apetite", 
    "apito", "aplauso", "apogeu", "apontar", "apos", "aprender", "aprovar", 
    "aquecedor", "aquilo", "arame", "aranha", "arara", "arbusto", "arca", 
    "ardente", "areia", "arfar", "argola", "arma", "aroma", "arpoar", "arquivo", 
    "arraia", "arrancar", "arrasto", "arroz", "arte", "artista", "arvore", 
    "asas", "asfalto", "aspirador", "assado", "assento", "assinar", "assobio", 
    "assustar", "astuto", "atacar", "ate", "aterro", "atitude", "atleta", 
    "atracao", "atras", "atriz", "aturar", "audivel", "aula", "aumento", 
    "aurora", "autentico", "autor", "autoria", "avaliar", "avancar", "ave", 
    "avental", "aviao", "avisar", "avistar", "avivar", "avo", "azedo", "azul", 
    "babador", "babuino", "bacia", "bagunca", "baia", "bailarina", "baioneta", 
    "baixo", "bala", "balde", "baleia", "baliza", "bambu", "banana", "bandeira", 
    "banho", "banquete", "baralho", "barba", "barco", "barraca", "barulho", 
    "base", "bastao", "batata", "batedor", "batida", "batom", "batucar", 
    "bazar", "beber", "beijo", "beira", "belo", "bem", "bengala", "berco", 
    "berrar", "besta", "bexiga", "bezerro", "bicho", "bicicleta", "bife", 
    "bigode", "bilhete", "bingo", "biologia", "biscoito", "bispo", "bloco", 
    "blusa", "boate", "bobagem", "boca", "bode", "boi", "boia", "bola", 
    "bolha", "bolo", "bolsa", "bomba", "bonde", "bonito", "borboleta", "borda", 
    "borracha", "bosque", "bota", "botao", "bote", "botina", "boxe", "branco", 
    "brasa", "bravo", "breu", "briga", "brilho", "brincar", "brisa", "broa", 
    "broche", "bronze", "broto", "bruxa", "bucho", "bule", "buraco", "busca", 
    "busto", "buzina", "caatinga", "cabelo", "cabo", "cacador", "cachorro", 
    "cadeado", "cafune", "caixa", "cajado", "calango", "calca", "calda", 
    "califa", "calma", "calo", "caloria", "cama", "camada", "cambista", 
    "camelo", "camisa", "campo", "canal", "canela", "canguru", "canhao", 
    "canivete", "canoa", "cansado", "cantar", "canudo", "capaz", "capela", 
    "capim", "capitulo", "capote", "captar", "capuz", "caracol", "carbonizar", 
    "cardume", "careca", "carga", "carimbo", "carne", "caro", "carro", 
    "carta", "carvao", "casaco", "casca", "casebre", "castelo", "catapora", 
    "cativeiro", "catraca", "caule", "causar", "cautelar", "cavalo", "caverna", 
    "caxumba", "cebola", "cedo", "cegonha", "cego", "ceifa", "celular", 
    "cenoura", "censo", "centro", "cerâmica", "cerca", "certo", "cervo", 
    "cesariana", "cesto", "cetro", "cha", "chaleira", "chama", "chance", 
    "chapeu", "charque", "chato", "chave", "chefe", "chegada", "cheio", 
    "cheiro", "chicote", "chifre", "chinelo", "chocalho", "chover", "chumbo", 
    "chupar", "chuva", "cicatriz", "cigana", "cimento", "cinema", "cingir", 
    "cinto", "cinza", "circo", "cirurgia", "citar", "clarear", "clero", 
    "clicar", "cliente", "clone", "clube", "coado", "coagir", "cobertor", 
    "cobra", "cocada", "coelho", "coentro", "coeso", "cogumelo", "coice", 
    "coisa", "colar", "coleira", "colher", "colmeia", "colono", "coluna", 
    "comando", "combinar", "comer", "comida", "comover", "comprar", "comum", 
    "concha", "condor", "conectar", "confuso", "conhecer", "conselho", "contar", 
    "conversa", "convite", "copo", "coragem", "cordas", "coro", "corpo", 
    "correio", "cortar", "coruja", "corvo", "coser", "costas", "couro", 
    "covarde", "coxa", "cozinha", "cracha", "crânio", "cratera", "cravo", 
    "creche", "creme", "crespo", "criado", "crise", "croqui", "cruel", 
    "cubo", "cueca", "cuidado", "cujo", "culatra", "culpa", "cume", "cunhado", 
    "cupido", "curar", "curioso", "curso", "curto", "cutucar", "dado", 
    "dama", "danca", "dardo", "datar", "debater", "decente", "dedo", 
    "defesa", "degrau", "deitar", "delator", "demora", "dente", "depenar", 
    "depois", "desafio", "descanso", "desenho", "desfile", "desgaste", 
    "desova", "despedir", "destino", "desuso", "detalhe", "deusa", "devagar", 
    "dever", "devoto", "dia", "diabo", "diagrama", "diamante", "diante", 
    "dica", "didatico", "dieta", "difícil", "digitar", "diluir", "dinamite", 
    "dinheiro", "diodo", "direto", "disco", "disputa"
};

const char *esp_word_bank1[491] = {
    "a", "abajo", "abandonar", "abierto", "abogado", "abril", "abrir", "absoluto", "abuelo", "acabar",
    "acaso", "accion", "aceptar", "acercar", "acero", "acido", "acordar", "acto", "actuar", "acuerdo",
    "adelante", "ademas", "adentro", "admitir", "adoptar", "adquirir", "adulto", "afectar", "afirmar", "afuera",
    "agente", "agosto", "agua", "agudo", "ahi", "ahora", "aire", "alarma", "alba", "alcanzar",
    "alegre", "alejar", "algo", "algun", "alma", "almacen", "alto", "amar", "ambos", "amenazar",
    "amigo", "amor", "amplio", "analizar", "anciano", "andar", "angulo", "animal", "anoche", "ante",
    "anterior", "antes", "antiguo", "anunciar", "anadir", "apagar", "aparato", "apenas", "aplicar", "apoyo",
    "aprender", "aprobar", "aprovechar", "aquel", "aquello", "aqui", "arma", "arriba", "arte", "artista",
    "asegurar", "asesino", "asistir", "asunto", "ataque", "atencion", "atender", "atras", "aumentar", "aun",
    "aunque", "autor", "avanzar", "avion", "ayer", "ayuda", "ayudar", "azul", "bajo", "barato",
    "barba", "barco", "base", "bastar", "bata", "batalla", "beber", "bebida", "bello", "besar",
    "biblioteca", "bien", "blanco", "boca", "bondad", "bonito", "bosque", "brazo", "breve", "brillar",
    "bueno", "buscar", "caballo", "cabeza", "cabo", "cada", "cadena", "caer", "cafe", "caja",
    "calcular", "calidad", "caliente", "calle", "cama", "cambio", "camino", "campo", "cantar", "cantidad",
    "capaz", "capital", "cara", "caracter", "carbono", "cargo", "carne", "caro", "carta", "casa",
    "caso", "castigo", "causa", "cazar", "cebolla", "celebrar", "central", "centro", "cereza", "cero",
    "cerrar", "cielo", "ciencia", "ciento", "cierto", "cinco", "cine", "circular", "circulo", "ciudad",
    "civil", "claro", "clase", "clave", "cliente", "clima", "cobrar", "cocina", "codigo", "coger",
    "cola", "colgar", "colina", "color", "comando", "comer", "comico", "comida", "como", "comodo",
    "compania", "compartir", "completo", "comprar", "comun", "con", "concepto", "concierto", "condicion", "conducir",
    "conectar", "confiar", "confuso", "conocer", "consejo", "consentir", "contar", "contener", "contestar", "continuar",
    "contra", "control", "convencer", "corazon", "correr", "cortar", "corto", "cosa", "costa", "crear",
    "crecer", "creer", "crimen", "cristal", "cruzar", "cuadro", "cual", "cuando", "cuanto", "cuarto",
    "cuatro", "cubico", "cuenta", "cuerpo", "cuesta", "cuidar", "culpa", "culto", "cumplir", "cuna",
    "cuento", "cuerda", "cuestion", "cuidado", "cuyo", "dado", "dama", "danza", "dar", "dato",
    "deber", "debajo", "diciembre", "decir", "dedo", "defender", "definir", "dejar", "delante", "demanda",
    "demas", "demostrar", "derecho", "derrota", "desde", "deseo", "desfile", "despues", "destino", "detalle",
    "detener", "devolver", "dia", "diablo", "diario", "dibujo", "diciembre", "diente", "diferir", "dificil",
    "dinero", "directo", "dirigir", "disco", "diseno", "disparo", "distinto", "diverso", "divertir", "doble",
    "doctor", "documento", "dolor", "domingo", "donde", "dormir", "dosis", "drama", "droga", "dueno",
    "duda", "duro", "echar", "economia", "edad", "edificio", "educar", "efecto", "ejemplo", "ejercito",
    "el", "elefante", "elegir", "elemento", "elevar", "elite", "ella", "empezar", "empresa", "enano",
    "encender", "encontrar", "enero", "energia", "enfermo", "enorme", "ensayo", "entender", "entero", "entonces",
    "entrada", "entrar", "envio", "epoca", "equipo", "error", "escala", "escena", "esclavo", "escoba",
    "escribir", "escritor", "escudo", "escuela", "esfuerzo", "eso", "espacio", "espada", "espejo", "esperar",
    "esposa", "esposo", "esta", "estado", "estilo", "estimar", "estomago", "estrella", "estudiar", "etapa",
    "eterno", "europa", "evitar", "exacto", "examen", "exigir", "exito", "explicar", "explorar", "exportar",
    "exterior", "extra", "fabricar", "facil", "factor", "faena", "falda", "fallar", "falso", "fama",
    "familia", "famoso", "favor", "febrero", "fecha", "feliz", "feo", "feria", "feroz", "fiambre",
    "fiebre", "fiel", "fiesta", "figura", "fijar", "fila", "fin", "finca", "fingir", "fino",
    "firma", "flaco", "flor", "fogata", "fondo", "forma", "fortuna", "foto", "fracaso", "francia",
    "frase", "frecuente", "freno", "fresa", "fresco", "frio", "frontera", "fruta", "fuego", "fuente",
    "fuerza", "fuga", "fumar", "funcion", "funda", "futuro", "gafas", "gallo", "ganar", "garganta",
    "gasolina", "gastar", "gato", "general", "gente", "gestion", "gigante", "girasol", "gloria", "gobierno",
    "golpe", "goma", "gordo", "gorra", "gota", "gozar", "gracia", "grado", "gran", "grande",
    "grano", "grasa", "grave", "gris", "gritar", "grueso", "grupo", "guante", "guapo", "guardar",
    "guerra", "guia", "gustar", "gusto", "haber", "habito", "hablar", "hacer", "hacha", "hallar",
    "hambre", "harina", "hasta", "hecho", "helado", "herida", "hermano", "heroe", "hervir", "hielo",
    "hierro", "hijo", "historia", "hondo", "honor", "hora", "hormiga", "hotel", "hoyo", "huevo",
    "huir"
};

const char *esp_word_bank2[491] = {
    "oasis", "objeto", "obligar", "obra", "observar", "obtener", "ocasion", "oceano", "ocho", "ocio",
    "ocre", "octubre", "oculto", "ocupar", "ocurrir", "odiar", "odio", "oeste", "ofender", "oferta",
    "oficial", "ofrecer", "oido", "oir", "ojo", "ola", "oleada", "olfato", "oliva", "olmo",
    "olor", "olvidar", "ombligo", "onda", "operar", "opinar", "oponer", "optar", "oracion", "orden",
    "oreja", "organo", "orgullo", "origen", "orilla", "oro", "orquesta", "oruga", "osar", "oscuro",
    "oso", "ostra", "otoño", "otro", "oveja", "oxido", "oyente", "pacto", "padre", "pagar",
    "pais", "paja", "pajaro", "palabra", "palco", "palma", "pan", "panal", "panico", "pantalla",
    "pantera", "panuelo", "papa", "papel", "par", "parada", "parar", "parcela", "pared", "pareja",
    "parir", "paro", "parte", "partir", "pasa", "pasado", "pasar", "pasear", "paso", "pasta",
    "pata", "patio", "patria", "pausa", "pauta", "paz", "peaje", "pecado", "pecho", "pedal",
    "pedazo", "pedir", "pegar", "peine", "pelar", "pelicula", "peligro", "pelo", "pelota", "pena",
    "pensar", "peor", "pepino", "pequeño", "pera", "perder", "perdon", "perfil", "perico", "perla",
    "permitir", "perro", "persona", "pesar", "pesca", "peso", "pestana", "petroleo", "pez", "picar",
    "pie", "piedra", "pierna", "pieza", "pila", "piloto", "pimienta", "pino", "pintar", "pinza",
    "piojo", "pipa", "pirata", "pisar", "piscina", "piso", "pista", "piston", "pizarra", "placa",
    "plan", "planta", "plata", "playa", "plaza", "plomo", "pluma", "plural", "pobre", "poco",
    "poder", "poema", "poesia", "pollo", "polvo", "pomada", "pomo", "poner", "porcion", "portal",
    "posada", "poseer", "posible", "poste", "potro", "pozo", "practica", "precio", "preferir", "pregunta",
    "premio", "preparar", "presencia", "presidente", "prestar", "pretender", "prima", "primo", "principal", "prisa",
    "privar", "probar", "problema", "proceso", "producto", "profesor", "programa", "prohibir", "prometer", "pronto",
    "propio", "proteger", "provecho", "proyecto", "prueba", "publico", "pueblo", "puerta", "puesto", "pulga",
    "pulir", "pulmon", "pulpo", "pulso", "punta", "punto", "punzon", "pupila", "pureza", "puro",
    "quedar", "queja", "quemar", "querer", "queso", "quieto", "quimica", "quitar", "rabia", "rabo",
    "racimo", "racion", "radar", "radio", "raiz", "rama", "rampa", "rango", "rapido", "raro",
    "rata", "rato", "rayo", "raza", "razon", "reacion", "real", "rebanada", "rebote", "recado",
    "receptor", "receta", "recibir", "recoger", "recreo", "recto", "recuerdo", "red", "redondo", "reducir",
    "reflejo", "reforma", "refran", "refresco", "regalo", "regar", "regir", "regla", "regreso", "rehusar",
    "reino", "reir", "reja", "relacion", "relampago", "relato", "relevo", "reloj", "remar", "remedio",
    "remo", "remoto", "rencor", "rendir", "renta", "reparto", "repetir", "reposo", "res", "rescate",
    "reserva", "resina", "resistir", "respeto", "resto", "resultar", "retirar", "retrato", "reunion", "revelar",
    "revista", "rey", "rezar", "rico", "riego", "rienda", "riesgo", "rifa", "rigido", "rima",
    "rincon", "rio", "riqueza", "risa", "ritmo", "rival", "robar", "roble", "roce", "rocio",
    "rodar", "rodilla", "roer", "rogar", "rojo", "rol", "romano", "romper", "ron", "ronco",
    "ronda", "ropa", "ropero", "rosa", "rostro", "rotar", "rubi", "rubio", "rudo", "rueda",
    "rugir", "ruido", "ruina", "ruleta", "rulo", "rumbo", "rumor", "ruptura", "rural", "ruso",
    "rutina", "saber", "sabio", "sable", "sabor", "sabroso", "sacar", "sacerdote", "saco", "sacudir",
    "sagrado", "sala", "salario", "salchicha", "saldo", "salida", "salir", "salmon", "salon", "salsa",
    "salto", "salud", "salvar", "sanar", "sancio", "sandia", "sangre", "sanidad", "sano", "santo",
    "sapo", "saque", "sardina", "sarten", "sastre", "satelite", "satisfacer", "sauce", "saurio", "sazon",
    "secar", "seccion", "seco", "secreto", "sector", "sed", "seda", "seguir", "segundo", "seguro",
    "seis", "seleccion", "sello", "selva", "semana", "semilla", "sencillo", "sendero", "senor", "sensacion",
    "sentar", "sentir", "senal", "senor", "separar", "sepia", "sequia", "ser", "serie", "sermon",
    "serpiente", "servir", "sesenta", "sesion", "seta", "setenta", "sexo", "sexto", "sidra", "siempre",
    "sierra", "siesta", "siete", "siglo", "signo", "siguiente", "silbar", "silencioso", "silla", "simbolo",
    "simio", "simple", "sin", "sincero", "sino", "sintoma", "siquiera", "sistema", "sitio", "situar",
    "sobre", "sociedad", "socio", "sodio", "sol", "solapa", "soldado", "soledad", "solo", "soltar",
    "solucion", "sombra", "sombrero", "sonar", "sonido", "sonreir", "sonrisa", "sopa", "soplar", "soporte",
    "sordo", "sorpresa", "sorteo", "sostener", "sotano", "suave", "subir", "suceso", "sudor", "suegra",
    "sueldo", "suelo", "sueno", "suerte", "sufrir", "sujetar", "sultán", "sumar", "superar", "suplir",
    "suponer"
};

const char *esp_word_bank3[491] = {
    "abanico", "abdomen", "abeja", "abismo", "abrelatas", "abrigo", "abrumar", "abuelito", "abundar", "academia",
    "acantilado", "acceder", "accidente", "acechar", "acelerar", "acento", "aceptable", "acera", "acertijo", "aclarar",
    "acomodar", "aconsejar", "acoplar", "acorazado", "acostumbrar", "actitud", "actriz", "actual", "acuarela", "acudir",
    "acumular", "acusar", "adaptar", "adecuado", "adherir", "adicto", "adivinar", "admirar", "adolescente", "adoptivo",
    "adorar", "adquirido", "adulto", "adversario", "afectar", "aficionado", "afligir", "afortunado", "agarrar", "agenda",
    "agitado", "agonia", "agradable", "agradecer", "agredir", "agrupar", "aguacate", "aguardar", "aguijon", "aguja",
    "ahogar", "ahorrar", "ahumar", "airear", "aislar", "ajedrez", "ajeno", "ajetreo", "ajustar", "alabanza",
    "alacran", "alambre", "alargar", "alarma", "albergar", "albino", "alboroto", "alcachofa", "alcalde", "alcance",
    "alcohol", "aldea", "aleatorio", "alejar", "alergia", "aleta", "alfabeto", "alfiler", "alga", "algoritmo",
    "aliento", "aliviar", "aljibe", "allanar", "almeja", "almohada", "alocado", "alquiler", "alterar", "altivo",
    "altura", "aludir", "alumno", "alzar", "amable", "amapola", "ambicion", "amenaza", "amigo", "amistad",
    "amnesia", "amonestar", "amorfo", "amparo", "ampliar", "ampolla", "analfabeto", "anarquia", "ancla", "andamio",
    "andrajoso", "anecdota", "angel", "angosto", "anhelar", "anillo", "animado", "aniversario", "anotar", "ansiedad",
    "antena", "antiguo", "anular", "anuncio", "anormal", "antepasado", "anterior", "antibiotico", "antiguo", "antologia",
    "antorcha", "anual", "anudar", "anunciar", "anzuelo", "apagado", "aparcar", "apasionado", "apego", "apellido",
    "apetito", "apio", "aplaudir", "aplicar", "apodo", "apostar", "apoyar", "aprender", "apresurar", "aprobado",
    "aprovechar", "apto", "apuesta", "apuro", "aquello", "arabia", "arado", "arana", "arar", "arbitro",
    "arbol", "arca", "archivo", "arder", "ardilla", "arduo", "arena", "arete", "argelia", "argumento",
    "aridez", "arisco", "arma", "armonia", "arnes", "aro", "arpia", "arqueologia", "arrancar", "arrastrar",
    "arrebatar", "arreglar", "arrepentir", "arriba", "arriesgar", "arrogante", "arroyo", "arruinar", "arte", "artesania",
    "artista", "asar", "asbesto", "ascensor", "asco", "asegurar", "asentir", "asesinar", "asfalto", "asiento",
    "asimilar", "asistir", "asno", "asombro", "aspar", "aspecto", "aspiradora", "astilla", "astro", "astuto",
    "asumir", "asustar", "atajar", "ataud", "atender", "ateo", "aterrizar", "atesorar", "atlas", "atleta",
    "atmosfera", "atomo", "atraer", "atras", "atreverse", "atrocidad", "atun", "audaz", "audio", "auge",
    "aula", "aumentar", "aura", "ausente", "autentico", "autobus", "automatico", "autorizar", "aval", "avance",
    "avaricia", "avaro", "ave", "avellana", "avena", "aventura", "avergonzar", "avestruz", "avioneta", "avisar",
    "aviso", "ayudante", "azafata", "azar", "azote", "azucar", "azufre", "azul", "babosa", "bache",
    "bahia", "bailar", "bajar", "bala", "balanza", "balcon", "balde", "bambu", "banana", "banda",
    "banquete", "baquero", "barato", "barbacoa", "barca", "baritono", "barniz", "barro", "basar", "basico",
    "basura", "batalla", "bateria", "batir", "batuta", "baul", "bautizar", "bebedor", "beca", "bedel",
    "beige", "belleza", "bendecir", "beneficio", "besar", "bestia", "bicho", "bienestar", "bigote", "billete",
    "biografia", "bisabuelo", "bisturi", "blanco", "blando", "bloque", "bobina", "boca", "bocina", "boda",
    "bofetada", "bogar", "boicot", "bola", "bolero", "bolsillo", "bomba", "bondad", "bonito", "borde",
    "borrar", "bosque", "bota", "botella", "boxeo", "bozon", "bramar", "brazo", "brecha", "brisa",
    "broche", "broma", "bronce", "brote", "bruja", "bruma", "brusco", "bruto", "bucear", "bucle",
    "bueno", "bufanda", "bufon", "buhardilla", "buitre", "bulto", "burbuja", "burla", "buscar", "butaca",
    "buzon", "cabana", "cabello", "cabeza", "cable", "cabo", "cabra", "cacao", "cachorro", "cadaver",
    "cadena", "caer", "cafe", "caida", "caja", "calamar", "calcular", "caldera", "calificar", "callar",
    "calma", "calor", "calvo", "camara", "cambio", "camello", "camino", "campana", "canal", "canario",
    "cancelar", "candado", "canela", "canguro", "canon", "cansado", "cantar", "cantera", "canon", "caoba",
    "caos", "capataz", "capaz", "capital", "capitulo", "capricho", "capturar", "capucha", "cara", "caracter",
    "carbon", "carcajada", "carcel", "careta", "carga", "caricia", "carne", "caro", "carpintero", "carro",
    "carta", "casa", "casco", "casero", "caso", "castigo", "casual", "catarro", "catastrofe", "catre",
    "caucho", "causa", "cautivar", "cavar", "cazador", "cazo", "cebolla", "ceder", "cegar", "ceja",
    "celda", "celebrar", "celoso", "celta", "cemento", "cenar", "cenicero", "censo", "centavo", "cereal",
    "ceremonia", "cerrar", "certeza", "cesped", "cetro", "chacal","verja", "verso", "verter", "vestir", "veterano", "vez", "viaje", "vibrar", "vicio", "vida",
    "video", "viejo", "viento", "vientre", "viernes", "vigor", "vil", "villa", "vinagre", "vino",
    "violin", "viral", "virgen", "virtual", "virtud", "visor", "vista", "vitamina", "vivo", "vocablo",
    "vocal", "volcan", "volumen", "volver", "vomitar"
};
#endif

